[build]
  base = "/"
  publish = "out/"
  command = "npm run build && npm run export"

[context.production]
  command = "NODE_ENV=production npm run build && npm run export"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
